name: tip_quant
dependencies:
  - python>=3.6
  - shapely
  - pip
  - pip:
      - pandas
      - scikit-image
      - scipy
      - tqdm
      - numpy>=1.14
      - opencv-python>=3.3.0
      - toml
      - scikit-video
      - plotly
      - streamlit
      - kaleido
      - scikit-learn
